<a href="https://www.kaggle.com/code/baruaprantika/mlb-2-class-5-assignment?scriptVersionId=346574971" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [4]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [5]:
a=np.array([1,2])
print(a.ndim)

b=np.array([[1,2],[3,4]])
print(b.ndim)

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.ndim)

d=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
print(d.ndim)



1
2
3
4


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [6]:
x=np.arange(2).reshape(2)
print(x.ndim)
y=np.arange(4).reshape(2,2)
print(y.ndim)
z=np.arange(8).reshape(2,2,2)
print(z.ndim)
p=np.arange(16).reshape(2,2,2,2)
print(p.ndim)


1
2
3
4


# create array using ones and zeros

In [7]:
v=np.ones(3)
print(v)
w=np.zeros(2)
print(w)

[1. 1. 1.]
[0. 0.]


# using random

In [8]:
np.random.random((3,3))



array([[0.4472312 , 0.57614588, 0.01869754],
       [0.91829296, 0.17248152, 0.64701118],
       [0.56899547, 0.90469734, 0.64876405]])

# using linspace

In [9]:
np.linspace(1,20,5,dtype=int)

array([ 1,  5, 10, 15, 20])

# create 1D array of tip from tips dataframe

In [10]:
tip= tips['tip'].to_numpy()

# create 2D array of tip and total_bill form tips dataframe

In [11]:
tip1= tips[['tip','total_bill']].to_numpy()


# practice atleast 2 example for each using ndim, shape, size and itemsize

In [12]:
tip= tips['tip'].to_numpy()
print(tip.ndim)
print(tip.shape)
print(np.size(tip))
tip.itemsize
tip1= tips[['tip','total_bill']].to_numpy()
print(tip1.ndim)
print(tip1.shape)
print(np.size(tip1))
tip1.itemsize

1
(244,)
244
2
(244, 2)
488


8

# change data type and memory size of any np-array using astype()

In [13]:
print(tip1.dtype)
print(tip1.astype(int))
m= tip1.astype(np.float16)
m.itemsize

float64
[[ 1 16]
 [ 1 10]
 [ 3 21]
 [ 3 23]
 [ 3 24]
 [ 4 25]
 [ 2  8]
 [ 3 26]
 [ 1 15]
 [ 3 14]
 [ 1 10]
 [ 5 35]
 [ 1 15]
 [ 3 18]
 [ 3 14]
 [ 3 21]
 [ 1 10]
 [ 3 16]
 [ 3 16]
 [ 3 20]
 [ 4 17]
 [ 2 20]
 [ 2 15]
 [ 7 39]
 [ 3 19]
 [ 2 17]
 [ 2 13]
 [ 2 12]
 [ 4 21]
 [ 3 19]
 [ 1  9]
 [ 2 18]
 [ 3 15]
 [ 2 20]
 [ 3 17]
 [ 3 24]
 [ 2 16]
 [ 3 16]
 [ 2 18]
 [ 5 31]
 [ 2 16]
 [ 2 17]
 [ 3 13]
 [ 1  9]
 [ 5 30]
 [ 3 18]
 [ 5 22]
 [ 6 32]
 [ 2 28]
 [ 3 18]
 [ 2 12]
 [ 2 10]
 [ 5 34]
 [ 1  9]
 [ 4 25]
 [ 3 19]
 [ 3 38]
 [ 1 26]
 [ 1 11]
 [ 6 48]
 [ 3 20]
 [ 2 13]
 [ 1 11]
 [ 3 18]
 [ 2 17]
 [ 3 20]
 [ 2 16]
 [ 1  3]
 [ 2 20]
 [ 2 15]
 [ 1 12]
 [ 3 17]
 [ 3 26]
 [ 5 25]
 [ 2 14]
 [ 1 10]
 [ 3 17]
 [ 4 27]
 [ 3 22]
 [ 2 17]
 [ 3 19]
 [ 3 16]
 [ 1 10]
 [ 5 32]
 [ 2 15]
 [ 5 34]
 [ 2 13]
 [ 4 18]
 [ 5 24]
 [ 3 21]
 [ 3 28]
 [ 3 22]
 [ 1  5]
 [ 4 16]
 [ 3 22]
 [ 4 40]
 [ 4 27]
 [ 1 12]
 [ 3 21]
 [ 1 12]
 [ 2 11]
 [ 3 15]
 [ 2 44]
 [ 3 22]
 [ 4 20]
 [ 1 15]
 [ 4 20]
 [ 4 25]
 [ 3 18]
 [ 4 14]
 [

2

# create 2 same dimensional array and do scalar and vector operations

In [14]:
p=np.arange(16).reshape(2,8)
print(p)
q=np.arange(16,32).reshape(2,8)
print(q)
print(p*3)
print(q**3)
print(p+2*q)
print(2*p-q)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
[[ 0  3  6  9 12 15 18 21]
 [24 27 30 33 36 39 42 45]]
[[ 4096  4913  5832  6859  8000  9261 10648 12167]
 [13824 15625 17576 19683 21952 24389 27000 29791]]
[[32 35 38 41 44 47 50 53]
 [56 59 62 65 68 71 74 77]]
[[-16 -15 -14 -13 -12 -11 -10  -9]
 [ -8  -7  -6  -5  -4  -3  -2  -1]]


# find minimun and maximum tip

In [15]:
tip= tips['tip'].to_numpy()
tip.astype(int)
print(np.max(tip))
print(np.min(tip))


10.0
1.0


# find average total_bill and average tip

In [16]:
tb= tips['total_bill'].to_numpy()
print(np.mean(tb))
tip= tips['tip'].to_numpy()
print(np.mean(tip))

19.78594262295082
2.99827868852459


# find median total_bill

In [17]:
print(np.median(tb))

17.795


# find standard deviasion and variance of tip

In [18]:
print(np.std(tip))
print(np.var(tip))

1.3807999538298954
1.9066085124966412


# find log values of tip

In [19]:
print(np.log(tip))

[0.00995033 0.5068176  1.25276297 1.19694819 1.28370777 1.54968791
 0.69314718 1.137833   0.67294447 1.17248214 0.53649337 1.60943791
 0.45107562 1.09861229 1.10525683 1.36609165 0.51282363 1.31103188
 1.25276297 1.20896035 1.40609699 1.01160091 0.80200159 2.0255132
 1.1568812  0.85015093 0.69314718 0.69314718 1.45861502 1.09861229
 0.37156356 0.91629073 1.09861229 0.89608802 1.18478998 1.28093385
 0.69314718 1.12167756 0.83724752 1.60943791 0.80647587 0.93216408
 1.11841492 0.27763174 1.7227666  1.09861229 1.60943791 1.79175947
 0.71783979 1.09861229 0.91629073 0.95551145 1.64865863 0.44468582
 1.46787435 1.25561604 1.09861229 0.40546511 0.56531381 1.90657514
 1.16627094 0.69314718 0.68309684 1.32441896 0.97077892 1.14740245
 0.90421815 0.         0.69813472 0.73716407 0.67803354 1.09861229
 1.1442228  1.60943791 0.78845736 0.22314355 1.1249296  1.38629436
 1.09861229 0.99694863 1.09861229 1.22377543 0.60431597 1.60943791
 0.70803579 1.64287269 0.69314718 1.38629436 1.76644166 1.09861

# apply round, floor and ceil operation on tip array

In [20]:
print(np.round(tip))
print(np.floor(tip))
print(np.ceil(tip))

[ 1.  2.  4.  3.  4.  5.  2.  3.  2.  3.  2.  5.  2.  3.  3.  4.  2.  4.
  4.  3.  4.  3.  2.  8.  3.  2.  2.  2.  4.  3.  1.  2.  3.  2.  3.  4.
  2.  3.  2.  5.  2.  3.  3.  1.  6.  3.  5.  6.  2.  3.  2.  3.  5.  2.
  4.  4.  3.  2.  2.  7.  3.  2.  2.  4.  3.  3.  2.  1.  2.  2.  2.  3.
  3.  5.  2.  1.  3.  4.  3.  3.  3.  3.  2.  5.  2.  5.  2.  4.  6.  3.
  3.  4.  1.  4.  3.  5.  4.  2.  3.  2.  2.  3.  2.  3.  4.  2.  4.  4.
  4.  4.  3.  1.  4.  3.  4.  4.  5.  2.  2.  3.  2.  2.  2.  2.  3.  4.
  1.  2.  2.  2.  2.  3.  2.  2.  3.  1.  2.  2.  2.  3.  4.  7.  5.  5.
  2.  2.  1.  2.  2.  2.  2.  2.  3.  2.  2.  5.  5.  4.  3.  2.  4.  2.
  2.  2.  3.  3.  2.  4.  2.  2. 10.  3.  5.  3.  4.  3.  2.  2.  4.  4.
  4.  6.  4.  6.  3.  5.  4.  2.  4.  4.  2.  4.  3.  2.  4.  1.  2.  5.
  2.  2.  4.  2.  2.  2.  4.  3.  3.  3.  2.  2.  2.  5.  9.  2.  6.  1.
  3.  2.  1.  3.  2.  3.  2.  3.  2.  2.  2.  3.  3.  3.  2.  3.  3.  1.
  3.  1.  1.  1.  5.  6.  2.  2.  2.  3.]
[ 1.  1. 

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [21]:
a

array([1, 2])

In [22]:
b

array([[1, 2],
       [3, 4]])

In [23]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
print(a[2:3])
print(b[:,1:2])
print(b[1:2,0:2])
print(c[1,:,2:3])
print(c[0,:1])

[]
[[2]
 [4]]
[[3 4]]
[]
[[1 2]]


# stacking and spliting

In [25]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)
print(np.vstack((d,e)))
print(np.vsplit(e,3))

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]
[array([[28, 29, 30, 31, 32, 33, 34, 35, 36]]), array([[37, 38, 39, 40, 41, 42, 43, 44, 45]]), array([[46, 47, 48, 49, 50, 51, 52, 53, 54]])]


# use hstack() and vstack()

In [26]:
print(np.hstack((d,e)))
print(np.vstack((d,e)))

[[ 0  1  2  3  4  5  6  7  8 28 29 30 31 32 33 34 35 36]
 [ 9 10 11 12 13 14 15 16 17 37 38 39 40 41 42 43 44 45]
 [18 19 20 21 22 23 24 25 26 46 47 48 49 50 51 52 53 54]]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]


# use hsplit() and vsplit()

In [27]:
print(np.hsplit(e,1.5))
print(np.vsplit(d,3))

[array([[28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])]
[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]), array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]
